### ISSUE TITLE
i m getting error when i tried to build the helper library

### ISSUE THREAD

**Issue by AshNewar** [uzochukwueddie/jobberapp#1]
![image](https://github.com/uzochukwueddie/jobberapp/assets/122523482/d5c2f228-eb67-4eab-8ddf-430e855fc735)

Can u please help?

**Comment by ankouros** [comment]
yes, i see this issue a few days ago, it is about latest mongoose. I guess you have version 8.3.0.
you can force instalation of stable 8.1.0 mongoose that work fine.
edit your package,json and change mongoose version to 8.1.0, 
delete node_modules folder and package-lock.json

run :
npm install
npm run build 
and will build without problems

**Comment by AshNewar** [comment]
Thanks a lot 😁
